language: node_js

# Run tests on
node_js:
  - "8"
  - "9"
  - "10"

services:
  # Enable docker
  - docker

addons:
  apt:
    packages:
      # Get an updated version of docker
      # Disable to prevent timeout on login (bug introduced on 18.04 docker-ce)
      # - docker-ce

# Cache dependencies
cache:
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk/"

before_install:
  # Install gcloud and kubectl
  - source $TRAVIS_BUILD_DIR/scripts/install.sh
  # Auth gcloud and kubectl
  - source $TRAVIS_BUILD_DIR/scripts/credentials.sh

install:
  - npm install
  - npm install --save codacy-coverage

script:
  - npm run coverage
  - helm lint --set deployment.imageVersion=latest ./chart/rackian-api/

after_success:
  # Send coverage to codacy
  - cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/scripts/deploy.sh && bash $TRAVIS_BUILD_DIR/scripts/deploy.sh
