language: node_js

# Select latest version of Node 8
node_js:
  - "8"

services:
  # Enable docker
  - docker

addons:
  apt:
    packages:
      # Get an updated version of docker
      - docker-ce

# Cache dependencies
cache:
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk/"

before_install:
  # Install gcloud and kubectl
  - source $TRAVIS_BUILD_DIR/scripts/install.sh
  # Auth gcloud and kubectl
  - source $TRAVIS_BUILD_DIR/scripts/credentials.sh

install:
  - npm install
  - npm install --save codacy-coverage

script:
  - npm run coverage
  - helm lint --set deployment.imageVersion=latest

after_success:
  # Send coverage to codacy
  - cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/scripts/deploy.sh && sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
