version: '3'
services:
  sut:
    build:
      context: .
      dockerfile: ./rackian-api-test/Dockerfile
    command: npm test
    environment:
      - PORT
      - PAGE_SIZE_DEFAULT
      - PAGE_SIZE_MAX
      - DB_URI
      - DB_NAME
