version: '3'
services:
  rackian-api:
    build:
      context: .
      args:
      - PORT
    image: rackian-api
    environment:
    - PORT
    - PAGE_SIZE_DEFAULT
    - PAGE_SIZE_MAX
    - DB_URI
    - DB_NAME
