apiVersion: v1
kind: Service
metadata:
  name: api-staging
  namespace: rackian-cloud
  labels:
    app: api
    enviroment: staging
spec:
  selector:
    app: api-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10001
  type: NodePort
