apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.app }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}:{{ required "The deployment MUST have an imageVersion" .Values.deployment.imageVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        - configMapRef:
            name: {{ .Values.configMap.name }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
