apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.app }}
    enviroment: {{ .Values.environment }}
data:
  NODE_ENV: "production"
  PORT: "10001"
  PAGE_SIZE_DEFAULT: "20"
  PAGE_SIZE_MAX: "100"
  DB_NAME: "rackianCloudStaging"
